### ISSUE TITLE
description 

### ISSUE THREAD

**Issue by marzoukh** [rubiklabs/node-jacpol#1]
hi!
i am very interest by your project i tried to clone but i don't see any description about it, can you help me?

**Comment by ogeday26** [comment]
@marzoukh Hi, thank you for interest. The project is actually not quite finished yet. I'm trying to take the time to finish it. It will be a small part of a big project when it is finished. I'm considering offering support for Express.js directly. If you can contact me directly by e-mail, we can talk about whether the project meets your needs. my e-mail address is safa@rubiklabs.com
